FROM {{ runner.image }}
{-% if runner.apt_deps %}
RUN apt-get update && apt-get install -y {{ runner.apt_deps | safe }} && rm -rf /var/lib/apt/lists/*
{-% end %}
{-% for bin in bins %}
COPY {{ bin.source }} /usr/local/bin/
{-% end %}
CMD [{-% for bin in bins %}"{{ bin.name }}"{{ ", " if not loop.last else "" }}{-%end}]


